arangodb:
  restart: always
  environment:
    - "ARANGO_NO_AUTH=1"
  image: arangodb/arangodb:3.1.4
  volumes:
  - arangodata:/var/lib/arangodb3
  ports:
  - 8529:8529/tcp
  labels:
    io.rancher.container.hostname_override: container_name
